# Bean Overriding 허용 (XML 설정과 부트 자동 설정 충돌 방지)
spring.main.allow-bean-definition-overriding=true

# JSP View Resolver 설정
spring.mvc.view.prefix=/WEB-INF/jsp/egovframework/example/
spring.mvc.view.suffix=.jsp
